apiVersion: v1
kind: Secret
metadata:
  name: account-cluster-manager-fmthp-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: "account-cluster-manager-fmthp"
type: kubernetes.io/service-account-token
