apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: cartservice-network-delay
  namespace: online-boutique
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: cartservice
  delay:
    latency: "3000ms"
    correlation: "0"
    jitter: "0ms"
  duration: "15m"
