apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: productcatalogservice-cpu-stress
  namespace: online-boutique
spec:
  mode: one
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: productcatalogservice
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: "15m"
