apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: redis-cart-cpu-v3-burst
  namespace: online-boutique
spec:
  mode: one
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: redis-cart
  stressors:
    cpu:
      workers: 2
      load: 100
  duration: "35m"
