apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: redis-cart-pod-kill-v3
  namespace: online-boutique
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: redis-cart
  duration: "35m"
