apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: redis-cart-network-delay
  namespace: online-boutique
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: redis-cart
  delay:
    latency: "5000ms"   # 5秒延迟（正常 <1ms）
    correlation: "0"
    jitter: "0ms"
  duration: "15m"
